name: ci
on:
  push:
    branches:
      - main

env:
  IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/liatrio-apprenticeship-exercise:${{ github.run_number }}
  CONTAINER_NAME: liatrio-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Build Docker image
        run: docker buildx build -t ${{ env.IMAGE }} --load .

      - name: Run container on port 80
        run: docker run -d --name ${{ env.CONTAINER_NAME }} -p 80:3000 ${{ env.IMAGE }}

      - name: run tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Login to Docker Hub
        uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ env.IMAGE }} 

      - name: Deploy to EC2
        uses: appleboy/ssh-action@8743aa11bfbda97acb45c151ae7a2e0b203f1914
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ env.IMAGE }}
            docker rm -f ${{ env.CONTAINER_NAME }} || true
            docker run -d --name ${{ env.CONTAINER_NAME }} -p 80:3000 ${{ env.IMAGE }}
